apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sumot-mlops
spec:
  project: default
  source:
    repoURL: https://github.com/marcderoo/application-deployment.git
    targetRevision: main
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-marcdro
  syncPolicy:
    automated:
      selfHeal: true
